# Generated by Django 4.2.7 on 2025-08-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "title_es",
                    models.CharField(help_text="Spanish title", max_length=200),
                ),
                ("description", models.TextField()),
                ("description_es", models.TextField(help_text="Spanish description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("saving", "How to Start Saving"),
                            ("immigrants", "Financial Tips for Immigrants"),
                            ("myths", "Money Myths Debunked"),
                            ("investments", "Cultural Investment Examples"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="💰", max_length=50)),
                (
                    "estimated_time",
                    models.IntegerField(help_text="Estimated time in minutes"),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Advanced")],
                        default=1,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["order", "created_at"],},
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_es", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("content_es", models.TextField()),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("content", "Educational Content"),
                            ("calculator", "Interactive Calculator"),
                            ("story", "Story/Example"),
                            ("quiz", "Quiz/Assessment"),
                        ],
                        default="content",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "calculator_config",
                    models.JSONField(
                        blank=True, help_text="Configuration for calculators", null=True
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="learning_modules.learningmodule",
                    ),
                ),
            ],
            options={"ordering": ["order"],},
        ),
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tip_text", models.CharField(max_length=300)),
                ("tip_text_es", models.CharField(max_length=300)),
                ("is_highlighted", models.BooleanField(default=False)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tips",
                        to="learning_modules.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("question_es", models.CharField(max_length=500)),
                (
                    "is_myth",
                    models.BooleanField(
                        help_text="True if this is a myth, False if it's reality"
                    ),
                ),
                ("explanation", models.TextField()),
                ("explanation_es", models.TextField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="learning_modules.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_es", models.CharField(max_length=200)),
                ("scenario", models.TextField(help_text="The example scenario")),
                ("scenario_es", models.TextField()),
                (
                    "analogy",
                    models.TextField(help_text="How it relates to investing/saving"),
                ),
                ("analogy_es", models.TextField()),
                ("image_description", models.CharField(blank=True, max_length=200)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="learning_modules.lesson",
                    ),
                ),
            ],
        ),
    ]
